//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.fingerprints = new HashSet<fingerprint>();
            this.fingertemplates = new HashSet<fingertemplate>();
        }
    
        public long id { get; set; }
        public string matricNumber { get; set; }
        public string surname { get; set; }
        public string firstName { get; set; }
        public string otherName { get; set; }
        public string email { get; set; }
        public long departmentId { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime insertedDate { get; set; }
        public string insertedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fingerprint> fingerprints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fingertemplate> fingertemplates { get; set; }
    }
}
