//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class university
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public university()
        {
            this.faculties = new HashSet<faculty>();
        }
    
        public long id { get; set; }
        public string universityCode { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string password { get; set; }
        public System.DateTime insertedDate { get; set; }
        public string insertedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedBy { get; set; }
        public string universityName { get; set; }
        public string universityAddress { get; set; }
        public bool activate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faculty> faculties { get; set; }
    }
}
